# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 3rdparty/protobuf/args.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='3rdparty/protobuf/args.proto',
  package='gSMFRETda.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x33rdparty/protobuf/args.proto\x12\x0cgSMFRETda.pb\"T\n\x04p_ga\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0c\n\x04stop\x18\x03 \x01(\x05\x12\x0e\n\x06\x62\x65stfv\x18\x04 \x01(\x02\x12\x12\n\x06params\x18\x05 \x03(\x02\x42\x02\x10\x01\"\x12\n\x03p_n\x12\x0b\n\x03s_n\x18\x01 \x01(\x05\"\x14\n\x05p_sid\x12\x0b\n\x03sid\x18\x01 \x01(\x05\"\x14\n\x05p_cap\x12\x0b\n\x03\x63\x61p\x18\x01 \x01(\x05\"8\n\x05p_str\x12\x0f\n\x07histNum\x18\x01 \x01(\x05\x12\x0b\n\x03str\x18\x02 \x01(\t\x12\x11\n\x05ohist\x18\x03 \x03(\x02\x42\x02\x10\x01\"L\n\x03res\x12\x0c\n\x04ridx\x18\x01 \x01(\x05\x12\t\n\x01\x65\x18\x02 \x01(\x02\x12\x0c\n\x04hist\x18\x03 \x01(\x08\x12\x0b\n\x03idx\x18\x04 \x01(\t\x12\x11\n\x05shist\x18\x05 \x03(\x02\x42\x02\x10\x01\x62\x06proto3'
)




_P_GA = _descriptor.Descriptor(
  name='p_ga',
  full_name='gSMFRETda.pb.p_ga',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='gSMFRETda.pb.p_ga.idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='gSMFRETda.pb.p_ga.start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop', full_name='gSMFRETda.pb.p_ga.stop', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bestfv', full_name='gSMFRETda.pb.p_ga.bestfv', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='gSMFRETda.pb.p_ga.params', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=130,
)


_P_N = _descriptor.Descriptor(
  name='p_n',
  full_name='gSMFRETda.pb.p_n',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s_n', full_name='gSMFRETda.pb.p_n.s_n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=150,
)


_P_SID = _descriptor.Descriptor(
  name='p_sid',
  full_name='gSMFRETda.pb.p_sid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid', full_name='gSMFRETda.pb.p_sid.sid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=172,
)


_P_CAP = _descriptor.Descriptor(
  name='p_cap',
  full_name='gSMFRETda.pb.p_cap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cap', full_name='gSMFRETda.pb.p_cap.cap', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=194,
)


_P_STR = _descriptor.Descriptor(
  name='p_str',
  full_name='gSMFRETda.pb.p_str',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='histNum', full_name='gSMFRETda.pb.p_str.histNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='str', full_name='gSMFRETda.pb.p_str.str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ohist', full_name='gSMFRETda.pb.p_str.ohist', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=252,
)


_RES = _descriptor.Descriptor(
  name='res',
  full_name='gSMFRETda.pb.res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ridx', full_name='gSMFRETda.pb.res.ridx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='gSMFRETda.pb.res.e', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hist', full_name='gSMFRETda.pb.res.hist', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idx', full_name='gSMFRETda.pb.res.idx', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shist', full_name='gSMFRETda.pb.res.shist', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['p_ga'] = _P_GA
DESCRIPTOR.message_types_by_name['p_n'] = _P_N
DESCRIPTOR.message_types_by_name['p_sid'] = _P_SID
DESCRIPTOR.message_types_by_name['p_cap'] = _P_CAP
DESCRIPTOR.message_types_by_name['p_str'] = _P_STR
DESCRIPTOR.message_types_by_name['res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

p_ga = _reflection.GeneratedProtocolMessageType('p_ga', (_message.Message,), {
  'DESCRIPTOR' : _P_GA,
  '__module__' : '3rdparty.protobuf.args_pb2'
  # @@protoc_insertion_point(class_scope:gSMFRETda.pb.p_ga)
  })
_sym_db.RegisterMessage(p_ga)

p_n = _reflection.GeneratedProtocolMessageType('p_n', (_message.Message,), {
  'DESCRIPTOR' : _P_N,
  '__module__' : '3rdparty.protobuf.args_pb2'
  # @@protoc_insertion_point(class_scope:gSMFRETda.pb.p_n)
  })
_sym_db.RegisterMessage(p_n)

p_sid = _reflection.GeneratedProtocolMessageType('p_sid', (_message.Message,), {
  'DESCRIPTOR' : _P_SID,
  '__module__' : '3rdparty.protobuf.args_pb2'
  # @@protoc_insertion_point(class_scope:gSMFRETda.pb.p_sid)
  })
_sym_db.RegisterMessage(p_sid)

p_cap = _reflection.GeneratedProtocolMessageType('p_cap', (_message.Message,), {
  'DESCRIPTOR' : _P_CAP,
  '__module__' : '3rdparty.protobuf.args_pb2'
  # @@protoc_insertion_point(class_scope:gSMFRETda.pb.p_cap)
  })
_sym_db.RegisterMessage(p_cap)

p_str = _reflection.GeneratedProtocolMessageType('p_str', (_message.Message,), {
  'DESCRIPTOR' : _P_STR,
  '__module__' : '3rdparty.protobuf.args_pb2'
  # @@protoc_insertion_point(class_scope:gSMFRETda.pb.p_str)
  })
_sym_db.RegisterMessage(p_str)

res = _reflection.GeneratedProtocolMessageType('res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : '3rdparty.protobuf.args_pb2'
  # @@protoc_insertion_point(class_scope:gSMFRETda.pb.res)
  })
_sym_db.RegisterMessage(res)


_P_GA.fields_by_name['params']._options = None
_P_STR.fields_by_name['ohist']._options = None
_RES.fields_by_name['shist']._options = None
# @@protoc_insertion_point(module_scope)
